
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action newAction;

	private global::Gtk.Action openNetwork;

	private global::Gtk.Action saveNetwork;

	private global::Gtk.Action convertAction;

	private global::Gtk.Action trainNetwork;

	private global::Gtk.VBox vboxmain;

	private global::Gtk.Toolbar toolbar1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.VBox vbox1;

	private global::Gtk.Label layersNum;

	private global::Gtk.Entry entry2;

	private global::Gtk.Label label2;

	private global::Gtk.Entry entry3;

	private global::Gtk.Label label3;

	private global::Gtk.Entry entry4;

	private global::Gtk.HButtonBox hbuttonbox2;

	private global::Gtk.Entry entryOutput;

	private global::Gtk.Label label4;

	private global::Gtk.Button btnEvaluate;

	private global::Gtk.Entry entryInput;

	private global::Gtk.Label label1;

	private global::Gtk.HSeparator hseparator1;

	private global::Gtk.DrawingArea drawingarea;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.newAction = new global::Gtk.Action ("newAction", global::Mono.Unix.Catalog.GetString ("Create"), null, "gtk-new");
		this.newAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Create");
		w1.Add (this.newAction, null);
		this.openNetwork = new global::Gtk.Action ("openNetwork", global::Mono.Unix.Catalog.GetString ("Open"), null, "gtk-open");
		this.openNetwork.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open");
		w1.Add (this.openNetwork, null);
		this.saveNetwork = new global::Gtk.Action ("saveNetwork", global::Mono.Unix.Catalog.GetString ("Save"), null, "gtk-save");
		this.saveNetwork.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save");
		w1.Add (this.saveNetwork, null);
		this.convertAction = new global::Gtk.Action ("convertAction", null, null, "gtk-convert");
		w1.Add (this.convertAction, null);
		this.trainNetwork = new global::Gtk.Action ("trainNetwork", global::Mono.Unix.Catalog.GetString ("Train"), null, "gtk-select-font");
		this.trainNetwork.ShortLabel = global::Mono.Unix.Catalog.GetString ("Train");
		w1.Add (this.trainNetwork, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vboxmain = new global::Gtk.VBox ();
		this.vboxmain.Name = "vboxmain";
		this.vboxmain.Spacing = 6;
		// Container child vboxmain.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar1'><toolitem name='newAction' action='newAction'/><toolitem name='openNetwork' action='openNetwork'/><toolitem name='saveNetwork' action='saveNetwork'/><toolitem name='trainNetwork' action='trainNetwork'/></toolbar></ui>");
		this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
		this.toolbar1.Name = "toolbar1";
		this.toolbar1.ShowArrow = false;
		this.vboxmain.Add (this.toolbar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxmain [this.toolbar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vboxmain.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		this.vbox1.BorderWidth = ((uint)(3));
		// Container child vbox1.Gtk.Box+BoxChild
		this.layersNum = new global::Gtk.Label ();
		this.layersNum.Name = "layersNum";
		this.layersNum.LabelProp = global::Mono.Unix.Catalog.GetString ("layersNum");
		this.vbox1.Add (this.layersNum);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.layersNum]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.entry2 = new global::Gtk.Entry ();
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '●';
		this.vbox1.Add (this.entry2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.entry2]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("epochs");
		this.vbox1.Add (this.label2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label2]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.entry3 = new global::Gtk.Entry ();
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.IsEditable = true;
		this.entry3.InvisibleChar = '●';
		this.vbox1.Add (this.entry3);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.entry3]));
		w6.Position = 3;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("neurons in layers");
		this.vbox1.Add (this.label3);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label3]));
		w7.Position = 4;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.entry4 = new global::Gtk.Entry ();
		this.entry4.CanFocus = true;
		this.entry4.Name = "entry4";
		this.entry4.IsEditable = true;
		this.entry4.InvisibleChar = '●';
		this.vbox1.Add (this.entry4);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.entry4]));
		w8.Position = 5;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbuttonbox2 = new global::Gtk.HButtonBox ();
		this.hbuttonbox2.Name = "hbuttonbox2";
		this.vbox1.Add (this.hbuttonbox2);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbuttonbox2]));
		w9.Position = 6;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.entryOutput = new global::Gtk.Entry ();
		this.entryOutput.CanFocus = true;
		this.entryOutput.Name = "entryOutput";
		this.entryOutput.IsEditable = true;
		this.entryOutput.InvisibleChar = '●';
		this.vbox1.Add (this.entryOutput);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.entryOutput]));
		w10.PackType = ((global::Gtk.PackType)(1));
		w10.Position = 7;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("output:");
		this.vbox1.Add (this.label4);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label4]));
		w11.PackType = ((global::Gtk.PackType)(1));
		w11.Position = 8;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.btnEvaluate = new global::Gtk.Button ();
		this.btnEvaluate.CanFocus = true;
		this.btnEvaluate.Name = "btnEvaluate";
		this.btnEvaluate.UseUnderline = true;
		this.btnEvaluate.Label = global::Mono.Unix.Catalog.GetString ("Evaluate");
		this.vbox1.Add (this.btnEvaluate);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.btnEvaluate]));
		w12.PackType = ((global::Gtk.PackType)(1));
		w12.Position = 9;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.entryInput = new global::Gtk.Entry ();
		this.entryInput.CanFocus = true;
		this.entryInput.Name = "entryInput";
		this.entryInput.IsEditable = true;
		this.entryInput.InvisibleChar = '●';
		this.vbox1.Add (this.entryInput);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.entryInput]));
		w13.PackType = ((global::Gtk.PackType)(1));
		w13.Position = 10;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("input:");
		this.vbox1.Add (this.label1);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
		w14.PackType = ((global::Gtk.PackType)(1));
		w14.Position = 11;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator ();
		this.hseparator1.Name = "hseparator1";
		this.vbox1.Add (this.hseparator1);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator1]));
		w15.PackType = ((global::Gtk.PackType)(1));
		w15.Position = 12;
		w15.Expand = false;
		w15.Fill = false;
		this.hbox1.Add (this.vbox1);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox1]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.drawingarea = new global::Gtk.DrawingArea ();
		this.drawingarea.Name = "drawingarea";
		this.hbox1.Add (this.drawingarea);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.drawingarea]));
		w17.Position = 1;
		this.vboxmain.Add (this.hbox1);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vboxmain [this.hbox1]));
		w18.Position = 1;
		this.Add (this.vboxmain);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 567;
		this.DefaultHeight = 430;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.newAction.Activated += new global::System.EventHandler (this.OnNewActionActivated);
		this.openNetwork.Activated += new global::System.EventHandler (this.OnOpenActionActivated);
		this.saveNetwork.Activated += new global::System.EventHandler (this.OnSaveActionActivated);
		this.trainNetwork.Activated += new global::System.EventHandler (this.OnTrainNetworkActivated);
		this.btnEvaluate.Clicked += new global::System.EventHandler (this.OnBtnEvaluateClicked);
		this.drawingarea.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnDrawingAreaExposed);
		this.drawingarea.ScreenChanged += new global::Gtk.ScreenChangedHandler (this.OnDrawingareaScreenChanged);
		this.drawingarea.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnDrawingareaButtonPressEvent);
	}
}
