
// This file has been generated by the GUI designer. Do not modify.
namespace NAVY
{
	public partial class NeuronWindow
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Table table1;

		private global::Gtk.ComboBox comboboxFunction;

		private global::Gtk.Entry entryID;

		private global::Gtk.Entry entryValue;

		private global::Gtk.Label label5;

		private global::Gtk.Label label6;

		private global::Gtk.Label labelID;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget NAVY.NeuronWindow
			this.Name = "NAVY.NeuronWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Neuron details");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child NAVY.NeuronWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.table1.BorderWidth = ((uint)(3));
			// Container child table1.Gtk.Table+TableChild
			this.comboboxFunction = global::Gtk.ComboBox.NewText ();
			this.comboboxFunction.AppendText (global::Mono.Unix.Catalog.GetString ("Perceptron"));
			this.comboboxFunction.AppendText (global::Mono.Unix.Catalog.GetString ("Input"));
			this.comboboxFunction.AppendText (global::Mono.Unix.Catalog.GetString ("Output"));
			this.comboboxFunction.Name = "comboboxFunction";
			this.table1.Add (this.comboboxFunction);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.comboboxFunction]));
			w1.TopAttach = ((uint)(2));
			w1.BottomAttach = ((uint)(3));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryID = new global::Gtk.Entry ();
			this.entryID.CanFocus = true;
			this.entryID.Name = "entryID";
			this.entryID.IsEditable = true;
			this.entryID.InvisibleChar = '●';
			this.table1.Add (this.entryID);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryID]));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryValue = new global::Gtk.Entry ();
			this.entryValue.CanFocus = true;
			this.entryValue.Name = "entryValue";
			this.entryValue.IsEditable = true;
			this.entryValue.InvisibleChar = '●';
			this.table1.Add (this.entryValue);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryValue]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Value");
			this.table1.Add (this.label5);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.label5]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xalign = 0F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Transfer function");
			this.label6.Justify = ((global::Gtk.Justification)(1));
			this.table1.Add (this.label6);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.label6]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelID = new global::Gtk.Label ();
			this.labelID.Name = "labelID";
			this.labelID.Xalign = 0F;
			this.labelID.LabelProp = global::Mono.Unix.Catalog.GetString ("ID");
			this.table1.Add (this.labelID);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelID]));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox2.Add (this.table1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.table1]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 336;
			this.DefaultHeight = 144;
			this.Show ();
		}
	}
}
